//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.04 at 03:04:02 PM EST 
//


package dev.igorartsoft.hierarchical.data.xml.jasperreports.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}plot"/>
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}xAxisLabelExpression" minOccurs="0"/>
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}xAxisFormat" minOccurs="0"/>
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}yAxisLabelExpression" minOccurs="0"/>
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}yAxisFormat" minOccurs="0"/>
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}domainAxisMinValueExpression" minOccurs="0"/>
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}domainAxisMaxValueExpression" minOccurs="0"/>
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}rangeAxisMinValueExpression" minOccurs="0"/>
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}rangeAxisMaxValueExpression" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="scaleType">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="BothAxes"/>
 *             &lt;enumeration value="DomainAxis"/>
 *             &lt;enumeration value="RangeAxis"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "plot",
    "xAxisLabelExpression",
    "xAxisFormat",
    "yAxisLabelExpression",
    "yAxisFormat",
    "domainAxisMinValueExpression",
    "domainAxisMaxValueExpression",
    "rangeAxisMinValueExpression",
    "rangeAxisMaxValueExpression"
})
@XmlRootElement(name = "bubblePlot")
public class BubblePlot {

    @XmlElement(required = true)
    protected Plot plot;
    protected XAxisLabelExpression xAxisLabelExpression;
    protected XAxisFormat xAxisFormat;
    protected YAxisLabelExpression yAxisLabelExpression;
    protected YAxisFormat yAxisFormat;
    protected DomainAxisMinValueExpression domainAxisMinValueExpression;
    protected DomainAxisMaxValueExpression domainAxisMaxValueExpression;
    protected RangeAxisMinValueExpression rangeAxisMinValueExpression;
    protected RangeAxisMaxValueExpression rangeAxisMaxValueExpression;
    @XmlAttribute(name = "scaleType")
    protected String scaleType;

    /**
     * Gets the value of the plot property.
     * 
     * @return
     *     possible object is
     *     {@link Plot }
     *     
     */
    public Plot getPlot() {
        return plot;
    }

    /**
     * Sets the value of the plot property.
     * 
     * @param value
     *     allowed object is
     *     {@link Plot }
     *     
     */
    public void setPlot(Plot value) {
        this.plot = value;
    }

    /**
     * Gets the value of the xAxisLabelExpression property.
     * 
     * @return
     *     possible object is
     *     {@link XAxisLabelExpression }
     *     
     */
    public XAxisLabelExpression getXAxisLabelExpression() {
        return xAxisLabelExpression;
    }

    /**
     * Sets the value of the xAxisLabelExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link XAxisLabelExpression }
     *     
     */
    public void setXAxisLabelExpression(XAxisLabelExpression value) {
        this.xAxisLabelExpression = value;
    }

    /**
     * Gets the value of the xAxisFormat property.
     * 
     * @return
     *     possible object is
     *     {@link XAxisFormat }
     *     
     */
    public XAxisFormat getXAxisFormat() {
        return xAxisFormat;
    }

    /**
     * Sets the value of the xAxisFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link XAxisFormat }
     *     
     */
    public void setXAxisFormat(XAxisFormat value) {
        this.xAxisFormat = value;
    }

    /**
     * Gets the value of the yAxisLabelExpression property.
     * 
     * @return
     *     possible object is
     *     {@link YAxisLabelExpression }
     *     
     */
    public YAxisLabelExpression getYAxisLabelExpression() {
        return yAxisLabelExpression;
    }

    /**
     * Sets the value of the yAxisLabelExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link YAxisLabelExpression }
     *     
     */
    public void setYAxisLabelExpression(YAxisLabelExpression value) {
        this.yAxisLabelExpression = value;
    }

    /**
     * Gets the value of the yAxisFormat property.
     * 
     * @return
     *     possible object is
     *     {@link YAxisFormat }
     *     
     */
    public YAxisFormat getYAxisFormat() {
        return yAxisFormat;
    }

    /**
     * Sets the value of the yAxisFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link YAxisFormat }
     *     
     */
    public void setYAxisFormat(YAxisFormat value) {
        this.yAxisFormat = value;
    }

    /**
     * Gets the value of the domainAxisMinValueExpression property.
     * 
     * @return
     *     possible object is
     *     {@link DomainAxisMinValueExpression }
     *     
     */
    public DomainAxisMinValueExpression getDomainAxisMinValueExpression() {
        return domainAxisMinValueExpression;
    }

    /**
     * Sets the value of the domainAxisMinValueExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link DomainAxisMinValueExpression }
     *     
     */
    public void setDomainAxisMinValueExpression(DomainAxisMinValueExpression value) {
        this.domainAxisMinValueExpression = value;
    }

    /**
     * Gets the value of the domainAxisMaxValueExpression property.
     * 
     * @return
     *     possible object is
     *     {@link DomainAxisMaxValueExpression }
     *     
     */
    public DomainAxisMaxValueExpression getDomainAxisMaxValueExpression() {
        return domainAxisMaxValueExpression;
    }

    /**
     * Sets the value of the domainAxisMaxValueExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link DomainAxisMaxValueExpression }
     *     
     */
    public void setDomainAxisMaxValueExpression(DomainAxisMaxValueExpression value) {
        this.domainAxisMaxValueExpression = value;
    }

    /**
     * Gets the value of the rangeAxisMinValueExpression property.
     * 
     * @return
     *     possible object is
     *     {@link RangeAxisMinValueExpression }
     *     
     */
    public RangeAxisMinValueExpression getRangeAxisMinValueExpression() {
        return rangeAxisMinValueExpression;
    }

    /**
     * Sets the value of the rangeAxisMinValueExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link RangeAxisMinValueExpression }
     *     
     */
    public void setRangeAxisMinValueExpression(RangeAxisMinValueExpression value) {
        this.rangeAxisMinValueExpression = value;
    }

    /**
     * Gets the value of the rangeAxisMaxValueExpression property.
     * 
     * @return
     *     possible object is
     *     {@link RangeAxisMaxValueExpression }
     *     
     */
    public RangeAxisMaxValueExpression getRangeAxisMaxValueExpression() {
        return rangeAxisMaxValueExpression;
    }

    /**
     * Sets the value of the rangeAxisMaxValueExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link RangeAxisMaxValueExpression }
     *     
     */
    public void setRangeAxisMaxValueExpression(RangeAxisMaxValueExpression value) {
        this.rangeAxisMaxValueExpression = value;
    }

    /**
     * Gets the value of the scaleType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScaleType() {
        return scaleType;
    }

    /**
     * Sets the value of the scaleType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScaleType(String value) {
        this.scaleType = value;
    }

}
