//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.04 at 03:04:02 PM EST 
//


package dev.igorartsoft.hierarchical.data.xml.jasperreports.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for complexEvaluationTime.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="complexEvaluationTime">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Now"/>
 *     &lt;enumeration value="Report"/>
 *     &lt;enumeration value="Page"/>
 *     &lt;enumeration value="Column"/>
 *     &lt;enumeration value="Group"/>
 *     &lt;enumeration value="Band"/>
 *     &lt;enumeration value="Auto"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "complexEvaluationTime")
@XmlEnum
public enum ComplexEvaluationTime {

    @XmlEnumValue("Now")
    NOW("Now"),
    @XmlEnumValue("Report")
    REPORT("Report"),
    @XmlEnumValue("Page")
    PAGE("Page"),
    @XmlEnumValue("Column")
    COLUMN("Column"),
    @XmlEnumValue("Group")
    GROUP("Group"),
    @XmlEnumValue("Band")
    BAND("Band"),
    @XmlEnumValue("Auto")
    AUTO("Auto");
    private final String value;

    ComplexEvaluationTime(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ComplexEvaluationTime fromValue(String v) {
        for (ComplexEvaluationTime c: ComplexEvaluationTime.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
