//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.04 at 03:04:02 PM EST 
//


package dev.igorartsoft.hierarchical.data.xml.jasperreports.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}lowExpression"/>
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}highExpression"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "lowExpression",
    "highExpression"
})
@XmlRootElement(name = "dataRange")
public class DataRange {

    @XmlElement(required = true)
    protected LowExpression lowExpression;
    @XmlElement(required = true)
    protected HighExpression highExpression;

    /**
     * Gets the value of the lowExpression property.
     * 
     * @return
     *     possible object is
     *     {@link LowExpression }
     *     
     */
    public LowExpression getLowExpression() {
        return lowExpression;
    }

    /**
     * Sets the value of the lowExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link LowExpression }
     *     
     */
    public void setLowExpression(LowExpression value) {
        this.lowExpression = value;
    }

    /**
     * Gets the value of the highExpression property.
     * 
     * @return
     *     possible object is
     *     {@link HighExpression }
     *     
     */
    public HighExpression getHighExpression() {
        return highExpression;
    }

    /**
     * Sets the value of the highExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link HighExpression }
     *     
     */
    public void setHighExpression(HighExpression value) {
        this.highExpression = value;
    }

}
