//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.04 at 03:04:02 PM EST 
//


package dev.igorartsoft.hierarchical.data.xml.jasperreports.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}hyperlinkParameterExpression"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "hyperlinkParameterExpression"
})
@XmlRootElement(name = "hyperlinkParameter")
public class HyperlinkParameter {

    @XmlElement(required = true)
    protected HyperlinkParameterExpression hyperlinkParameterExpression;
    @XmlAttribute(name = "name", required = true)
    protected String name;

    /**
     * Gets the value of the hyperlinkParameterExpression property.
     * 
     * @return
     *     possible object is
     *     {@link HyperlinkParameterExpression }
     *     
     */
    public HyperlinkParameterExpression getHyperlinkParameterExpression() {
        return hyperlinkParameterExpression;
    }

    /**
     * Sets the value of the hyperlinkParameterExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link HyperlinkParameterExpression }
     *     
     */
    public void setHyperlinkParameterExpression(HyperlinkParameterExpression value) {
        this.hyperlinkParameterExpression = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
