//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.04 at 03:04:02 PM EST 
//


package dev.igorartsoft.hierarchical.data.xml.jasperreports.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}plot"/>
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}tickLabelFont" minOccurs="0"/>
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}valueDisplay" minOccurs="0"/>
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}dataRange"/>
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}meterInterval" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="shape">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="chord"/>
 *             &lt;enumeration value="circle"/>
 *             &lt;enumeration value="pie"/>
 *             &lt;enumeration value="dial"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="angle" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="units" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="tickInterval" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="meterColor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="needleColor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="tickColor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "plot",
    "tickLabelFont",
    "valueDisplay",
    "dataRange",
    "meterInterval"
})
@XmlRootElement(name = "meterPlot")
public class MeterPlot {

    @XmlElement(required = true)
    protected Plot plot;
    protected TickLabelFont tickLabelFont;
    protected ValueDisplay valueDisplay;
    @XmlElement(required = true)
    protected DataRange dataRange;
    protected List<MeterInterval> meterInterval;
    @XmlAttribute(name = "shape")
    protected String shape;
    @XmlAttribute(name = "angle")
    protected String angle;
    @XmlAttribute(name = "units")
    protected String units;
    @XmlAttribute(name = "tickInterval")
    protected String tickInterval;
    @XmlAttribute(name = "meterColor")
    protected String meterColor;
    @XmlAttribute(name = "needleColor")
    protected String needleColor;
    @XmlAttribute(name = "tickColor")
    protected String tickColor;

    /**
     * Gets the value of the plot property.
     * 
     * @return
     *     possible object is
     *     {@link Plot }
     *     
     */
    public Plot getPlot() {
        return plot;
    }

    /**
     * Sets the value of the plot property.
     * 
     * @param value
     *     allowed object is
     *     {@link Plot }
     *     
     */
    public void setPlot(Plot value) {
        this.plot = value;
    }

    /**
     * Gets the value of the tickLabelFont property.
     * 
     * @return
     *     possible object is
     *     {@link TickLabelFont }
     *     
     */
    public TickLabelFont getTickLabelFont() {
        return tickLabelFont;
    }

    /**
     * Sets the value of the tickLabelFont property.
     * 
     * @param value
     *     allowed object is
     *     {@link TickLabelFont }
     *     
     */
    public void setTickLabelFont(TickLabelFont value) {
        this.tickLabelFont = value;
    }

    /**
     * Gets the value of the valueDisplay property.
     * 
     * @return
     *     possible object is
     *     {@link ValueDisplay }
     *     
     */
    public ValueDisplay getValueDisplay() {
        return valueDisplay;
    }

    /**
     * Sets the value of the valueDisplay property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValueDisplay }
     *     
     */
    public void setValueDisplay(ValueDisplay value) {
        this.valueDisplay = value;
    }

    /**
     * Gets the value of the dataRange property.
     * 
     * @return
     *     possible object is
     *     {@link DataRange }
     *     
     */
    public DataRange getDataRange() {
        return dataRange;
    }

    /**
     * Sets the value of the dataRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataRange }
     *     
     */
    public void setDataRange(DataRange value) {
        this.dataRange = value;
    }

    /**
     * Gets the value of the meterInterval property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the meterInterval property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMeterInterval().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MeterInterval }
     * 
     * 
     */
    public List<MeterInterval> getMeterInterval() {
        if (meterInterval == null) {
            meterInterval = new ArrayList<MeterInterval>();
        }
        return this.meterInterval;
    }

    /**
     * Gets the value of the shape property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShape() {
        return shape;
    }

    /**
     * Sets the value of the shape property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShape(String value) {
        this.shape = value;
    }

    /**
     * Gets the value of the angle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAngle() {
        return angle;
    }

    /**
     * Sets the value of the angle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAngle(String value) {
        this.angle = value;
    }

    /**
     * Gets the value of the units property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnits() {
        return units;
    }

    /**
     * Sets the value of the units property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnits(String value) {
        this.units = value;
    }

    /**
     * Gets the value of the tickInterval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTickInterval() {
        return tickInterval;
    }

    /**
     * Sets the value of the tickInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTickInterval(String value) {
        this.tickInterval = value;
    }

    /**
     * Gets the value of the meterColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeterColor() {
        return meterColor;
    }

    /**
     * Sets the value of the meterColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeterColor(String value) {
        this.meterColor = value;
    }

    /**
     * Gets the value of the needleColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNeedleColor() {
        return needleColor;
    }

    /**
     * Sets the value of the needleColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNeedleColor(String value) {
        this.needleColor = value;
    }

    /**
     * Gets the value of the tickColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTickColor() {
        return tickColor;
    }

    /**
     * Sets the value of the tickColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTickColor(String value) {
        this.tickColor = value;
    }

}
