//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.04 at 03:04:02 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://jasperreports.sourceforge.net/jasperreports", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package dev.igorartsoft.hierarchical.data.xml.jasperreports.model;
