//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.04 at 03:04:02 PM EST 
//


package dev.igorartsoft.hierarchical.data.xml.jasperreports.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}bucket"/>
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}crosstabRowHeader" minOccurs="0"/>
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}crosstabTotalRowHeader" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="width" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="totalPosition" default="None">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="Start"/>
 *             &lt;enumeration value="End"/>
 *             &lt;enumeration value="None"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="headerPosition" default="Top">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="Top"/>
 *             &lt;enumeration value="Middle"/>
 *             &lt;enumeration value="Bottom"/>
 *             &lt;enumeration value="Stretch"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bucket",
    "crosstabRowHeader",
    "crosstabTotalRowHeader"
})
@XmlRootElement(name = "rowGroup")
public class RowGroup {

    @XmlElement(required = true)
    protected Bucket bucket;
    protected CrosstabRowHeader crosstabRowHeader;
    protected CrosstabTotalRowHeader crosstabTotalRowHeader;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "width", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String width;
    @XmlAttribute(name = "totalPosition")
    protected String totalPosition;
    @XmlAttribute(name = "headerPosition")
    protected String headerPosition;

    /**
     * Gets the value of the bucket property.
     * 
     * @return
     *     possible object is
     *     {@link Bucket }
     *     
     */
    public Bucket getBucket() {
        return bucket;
    }

    /**
     * Sets the value of the bucket property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bucket }
     *     
     */
    public void setBucket(Bucket value) {
        this.bucket = value;
    }

    /**
     * Gets the value of the crosstabRowHeader property.
     * 
     * @return
     *     possible object is
     *     {@link CrosstabRowHeader }
     *     
     */
    public CrosstabRowHeader getCrosstabRowHeader() {
        return crosstabRowHeader;
    }

    /**
     * Sets the value of the crosstabRowHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link CrosstabRowHeader }
     *     
     */
    public void setCrosstabRowHeader(CrosstabRowHeader value) {
        this.crosstabRowHeader = value;
    }

    /**
     * Gets the value of the crosstabTotalRowHeader property.
     * 
     * @return
     *     possible object is
     *     {@link CrosstabTotalRowHeader }
     *     
     */
    public CrosstabTotalRowHeader getCrosstabTotalRowHeader() {
        return crosstabTotalRowHeader;
    }

    /**
     * Sets the value of the crosstabTotalRowHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link CrosstabTotalRowHeader }
     *     
     */
    public void setCrosstabTotalRowHeader(CrosstabTotalRowHeader value) {
        this.crosstabTotalRowHeader = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWidth(String value) {
        this.width = value;
    }

    /**
     * Gets the value of the totalPosition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalPosition() {
        if (totalPosition == null) {
            return "None";
        } else {
            return totalPosition;
        }
    }

    /**
     * Sets the value of the totalPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalPosition(String value) {
        this.totalPosition = value;
    }

    /**
     * Gets the value of the headerPosition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeaderPosition() {
        if (headerPosition == null) {
            return "Top";
        } else {
            return headerPosition;
        }
    }

    /**
     * Sets the value of the headerPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeaderPosition(String value) {
        this.headerPosition = value;
    }

}
