//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.04 at 03:04:02 PM EST 
//


package dev.igorartsoft.hierarchical.data.xml.jasperreports.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}variableExpression" minOccurs="0"/>
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}initialValueExpression" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" default="java.lang.String" />
 *       &lt;attribute name="resetType" default="Report">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="None"/>
 *             &lt;enumeration value="Report"/>
 *             &lt;enumeration value="Page"/>
 *             &lt;enumeration value="Column"/>
 *             &lt;enumeration value="Group"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="resetGroup" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="incrementType" default="None">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="None"/>
 *             &lt;enumeration value="Report"/>
 *             &lt;enumeration value="Page"/>
 *             &lt;enumeration value="Column"/>
 *             &lt;enumeration value="Group"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="incrementGroup" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="calculation" default="Nothing">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="Nothing"/>
 *             &lt;enumeration value="Count"/>
 *             &lt;enumeration value="DistinctCount"/>
 *             &lt;enumeration value="Sum"/>
 *             &lt;enumeration value="Average"/>
 *             &lt;enumeration value="Lowest"/>
 *             &lt;enumeration value="Highest"/>
 *             &lt;enumeration value="StandardDeviation"/>
 *             &lt;enumeration value="Variance"/>
 *             &lt;enumeration value="System"/>
 *             &lt;enumeration value="First"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="incrementerFactoryClass" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "variableExpression",
    "initialValueExpression"
})
@XmlRootElement(name = "variable")
public class Variable {

    protected VariableExpression variableExpression;
    protected InitialValueExpression initialValueExpression;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "class")
    protected String clazz;
    @XmlAttribute(name = "resetType")
    protected String resetType;
    @XmlAttribute(name = "resetGroup")
    protected String resetGroup;
    @XmlAttribute(name = "incrementType")
    protected String incrementType;
    @XmlAttribute(name = "incrementGroup")
    protected String incrementGroup;
    @XmlAttribute(name = "calculation")
    protected String calculation;
    @XmlAttribute(name = "incrementerFactoryClass")
    protected String incrementerFactoryClass;

    /**
     * Gets the value of the variableExpression property.
     * 
     * @return
     *     possible object is
     *     {@link VariableExpression }
     *     
     */
    public VariableExpression getVariableExpression() {
        return variableExpression;
    }

    /**
     * Sets the value of the variableExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link VariableExpression }
     *     
     */
    public void setVariableExpression(VariableExpression value) {
        this.variableExpression = value;
    }

    /**
     * Gets the value of the initialValueExpression property.
     * 
     * @return
     *     possible object is
     *     {@link InitialValueExpression }
     *     
     */
    public InitialValueExpression getInitialValueExpression() {
        return initialValueExpression;
    }

    /**
     * Sets the value of the initialValueExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link InitialValueExpression }
     *     
     */
    public void setInitialValueExpression(InitialValueExpression value) {
        this.initialValueExpression = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClazz() {
        if (clazz == null) {
            return "java.lang.String";
        } else {
            return clazz;
        }
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClazz(String value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the resetType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResetType() {
        if (resetType == null) {
            return "Report";
        } else {
            return resetType;
        }
    }

    /**
     * Sets the value of the resetType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResetType(String value) {
        this.resetType = value;
    }

    /**
     * Gets the value of the resetGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResetGroup() {
        return resetGroup;
    }

    /**
     * Sets the value of the resetGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResetGroup(String value) {
        this.resetGroup = value;
    }

    /**
     * Gets the value of the incrementType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncrementType() {
        if (incrementType == null) {
            return "None";
        } else {
            return incrementType;
        }
    }

    /**
     * Sets the value of the incrementType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncrementType(String value) {
        this.incrementType = value;
    }

    /**
     * Gets the value of the incrementGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncrementGroup() {
        return incrementGroup;
    }

    /**
     * Sets the value of the incrementGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncrementGroup(String value) {
        this.incrementGroup = value;
    }

    /**
     * Gets the value of the calculation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCalculation() {
        if (calculation == null) {
            return "Nothing";
        } else {
            return calculation;
        }
    }

    /**
     * Sets the value of the calculation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCalculation(String value) {
        this.calculation = value;
    }

    /**
     * Gets the value of the incrementerFactoryClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncrementerFactoryClass() {
        return incrementerFactoryClass;
    }

    /**
     * Sets the value of the incrementerFactoryClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncrementerFactoryClass(String value) {
        this.incrementerFactoryClass = value;
    }

}
